---

- name: Converge
  hosts: all
  become: true

  vars:
    env: develop

    services_dir: /opt/services

    private_network: "{{ ansible_eth0['ipv4'] }}"
    public_network: "{{ ansible_eth0['ipv4'] }}"

    traefik:
      service: traefik.service.consul

      service_dir: "{{ services_dir }}/traefik"
      certs_dir: "{{ services_dir }}/traefik/certs"
      conf_dir: "{{ services_dir }}/traefik/conf.d"

      host: "{{ private_network.address }}"
      port: 80

      consul:
        enabled: false
        host: consul.service.consul
        port: 8500

      container:
        image: traefik
        name: traefik
        restart: always
        network: ''

        syslog:
          enabled: false
          host: unixgram:///dev/log
          tag: traefik

      exporter:
        enabled: yes

        host: "{{ private_network.address }}"
        port: 8080

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: Install test requirements
      apt: name=curl
